//! Runtime chrome geometry, in logical window pixels (before OS DPI).
//!
//! The winit UI thread uses one snapshot for both painting and hit testing.
//! Module accessors read this snapshot, including pure layout helpers that do
//! not carry a Theme. Document geometry, rulers, cursor glyphs and canvas grab
//! radii deliberately do not participate. Font sizes are scaled by TextContext.

use std::cell::RefCell;

#[derive(Clone, Debug)]
pub struct Metrics {
    pub ui_scale: f64,
    pub tooltip_font_size: f32,
    pub tooltip_pad: f64,
    pub tooltip_offset_x: f64,
    pub tooltip_offset_y: f64,
    pub tooltip_margin: f64,
    pub tooltip_flip_gap: f64,
    pub dock_tab_content_min_h: f32,
    pub dock_tab_content_max_h: f32,
    pub dock_tab_content_default_h: f32,
    pub palette_pw: f64,
    pub palette_field_h: f64,
    pub palette_row_h: f64,
    pub palette_pad: f64,
    pub about_width: f64,
    pub about_height: f64,
    pub about_corner_radius: f64,
    pub about_pad_x: f64,
    pub about_logo_y: f64,
    pub about_logo_w: f64,
    pub about_body_top: f64,
    pub about_link_gap: f64,
    pub about_wrap_w: f32,
    pub layout_master_min_w: f64,
    pub layout_master_max_w: f64,
    pub layout_tools_min_w: f64,
    pub layout_compact_breakpoint: f64,
    pub layout_compact_rail_w: f64,
    pub layout_dock_edge: f64,
    pub layout_dock_seam: f64,
    pub layout_stack_row_h: f64,
    pub layout_header_h: f64,
    pub layout_group_handle_h: f64,
    pub layout_flyout_w: f64,
    pub layout_flyout_h: f64,
    pub newdoc_fh: f64,
    pub newdoc_footer_h: f64,
    pub stroke_panel_w: f64,
    pub stroke_panel_h: f64,
    pub stroke_panel_pad: f64,
    pub stroke_panel_ctrl_x: f64,
    pub stroke_panel_btn_w: f64,
    pub stroke_panel_btn_h: f64,
    pub stroke_panel_btn_gap: f64,
    pub stroke_panel_field_w: f64,
    pub stroke_panel_step_w: f64,
    pub workspace_dialog_card_w: f64,
    pub workspace_dialog_card_h: f64,
    pub workspace_dialog_manage_w: f64,
    pub workspace_dialog_row_h: f64,
    pub workspace_dialog_list_top: f64,
    pub workspace_dialog_footer_h: f64,
    pub workspace_dialog_empty_h: f64,
    pub home_pad: f64,
    pub home_mark_size: f64,
    pub home_badge: f64,
    pub home_target_tile: f64,
    pub home_min_tile: f64,
    pub home_max_tile: f64,
    pub home_toolbar_h: f64,
    pub picker_w: f64,
    pub picker_h: f64,
    pub confirm_close_card_w: f64,
    pub confirm_close_card_h: f64,
    pub scroll_view_bar_w: f64,
    pub scroll_view_min_thumb: f64,
    pub blenddlg_w: f64,
    pub blenddlg_pad: f64,
    pub blenddlg_row_h: f64,
    pub blenddlg_row_gap: f64,
    pub blenddlg_field_h: f64,
    pub blenddlg_btn_h: f64,
    pub offsetdlg_w: f64,
    pub offsetdlg_pad: f64,
    pub offsetdlg_field_h: f64,
    pub offsetdlg_row_gap: f64,
    pub offsetdlg_label_w: f64,
    pub offsetdlg_btn_h: f64,
    pub xformdlg_w: f64,
    pub xformdlg_pad: f64,
    pub xformdlg_row_h: f64,
    pub xformdlg_radio_r: f64,
    pub xformdlg_dial_r: f64,
    pub xformdlg_field_w: f64,
    pub xformdlg_field_h: f64,
    pub xformdlg_label_w: f64,
    pub xformdlg_shear_label_w: f64,
    pub xformdlg_box_top_gap: f64,
    pub xformdlg_box_bottom_pad: f64,
    pub xformdlg_section_gap: f64,
    pub xformdlg_btn_h: f64,
    pub xformdlg_btn_w: f64,
    pub xformdlg_btn_gap: f64,
    pub xformdlg_bot_pad: f64,
    pub xformdlg_check_s: f64,
    pub xformdlg_axis_label_col: f64,
    pub chrome_panel_tab_close_w: f64,
    pub prefs_w: f64,
    pub prefs_h: f64,
    pub prefs_sidebar_w: f64,
    pub prefs_pad: f64,
    pub app_guides_rm_w: f64,
    pub app_guides_rm_row: f64,
    pub app_guides_rm_pad: f64,
    pub app_free_transform_ft_btn_w: f64,
    pub app_free_transform_ft_btn_h: f64,
    pub app_free_transform_ft_btn_gap: f64,
    pub app_free_transform_ft_pad: f64,
    pub app_app_bar_h: f64,
    pub app_tab_bar_h: f64,
    pub app_opt_bar_h: f64,
    pub app_chrome_top: f64,
    pub app_grab_slop: f64,
    pub app_rail_edge: f64,
    pub app_drag_threshold: f64,
    pub app_float_w: f64,
    pub app_float_h: f64,
    pub app_fm_row: f64,
    pub app_at_w: f64,
    pub app_at_row: f64,
    pub app_at_pad: f64,
    pub app_cm_w: f64,
    pub app_cm_row: f64,
    pub app_cm_sep: f64,
    pub app_cm_pad: f64,
    pub app_pm_w: f64,
    pub app_pm_row: f64,
    pub app_pm_sep: f64,
    pub app_pm_pad: f64,
    pub app_tool_flyout_w: f64,
    pub app_tool_flyout_row: f64,
    pub panels_gradient_natural_h: f64,
    pub panels_gradient_bar_h: f64,
    pub panels_gradient_stop_w: f64,
    pub panels_gradient_stop_h: f64,
    pub panels_gradient_field_h: f64,
    pub panels_gradient_chev_w: f64,
    pub panels_gradient_remove_drop: f64,
    pub panels_tools_cell: f64,
    pub panels_tools_top: f64,
    pub panels_tools_proxy_h: f64,
    pub panels_align_btn: f64,
    pub panels_align_gap: f64,
    pub panels_align_group_gap: f64,
    pub panels_align_label_drop: f64,
    pub panels_align_label_to_row: f64,
    pub panels_align_row_to_rule: f64,
    pub panels_align_after_rule: f64,
    pub panels_color_natural_h: f64,
    pub panels_color_recent_h: f64,
    pub panels_color_chip: f64,
    pub panels_color_slider_h: f64,
    pub panels_color_track_h: f64,
    pub panels_color_field_w: f64,
    pub panels_color_spec_h: f64,
    pub panels_pathfinder_btn: f64,
    pub panels_pathfinder_gap: f64,
    pub panels_row_h: f64,
    pub panels_pad: f64,
    pub panels_swatch: f64,
    pub panels_footer_h: f64,
    pub panels_layers_indent: f64,
    pub panels_layers_col: f64,
    pub panels_layers_search_h: f64,
    pub panels_transform_field_h: f64,
    pub panels_transform_gap: f64,
    pub panels_transform_loc: f64,
    pub panels_character_row_h: f64,
    pub panels_character_gap: f64,
    pub panels_character_field_h: f64,
    pub panels_paragraph_btn: f64,
    pub panels_paragraph_bgap: f64,
    pub panels_paragraph_field_h: f64,
    pub panels_paragraph_row: f64,
    pub shapedialog_spiral_btn: f64,
    pub shapedialog_spiral_btn_gap: f64,
    pub shapedialog_spiral_label_w: f64,
    pub shapedialog_spiral_top_pad: f64,
    pub shapedialog_spiral_bot_pad: f64,
    pub shapedialog_spiral_options_h: f64,
    pub shapedialog_w: f64,
    pub shapedialog_btn_h: f64,
    pub shapedialog_btn_w: f64,
    pub shapedialog_btn_gap: f64,
    pub shapedialog_gap_before_btns: f64,
    pub shapedialog_bot_pad: f64,
    pub shapedialog_sizing_pad_x: f64,
    pub shapedialog_sizing_top_pad: f64,
    pub shapedialog_sizing_field_h: f64,
    pub shapedialog_sizing_row_stride: f64,
    pub shapedialog_sizing_label_w: f64,
    pub shapedialog_sizing_link_w: f64,
    pub shapedialog_sizing_step_w: f64,
    pub shapedialog_arc_row_h: f64,
    pub shapedialog_arc_row_gap: f64,
    pub shapedialog_arc_label_w: f64,
    pub shapedialog_arc_top_pad: f64,
    pub shapedialog_arc_bot_pad: f64,
    pub shapedialog_arc_options_h: f64,
    pub context_bar_align_btn: f64,
    pub context_bar_align_gap: f64,
    pub context_bar_align_group: f64,
    pub context_bar_align_drop_w: f64,
    pub context_bar_align_width: f64,
    pub context_bar_anchor_btn: f64,
    pub context_bar_gap: f64,
    pub export_w: f64,
    pub export_h: f64,
    pub export_pad: f64,
    pub export_right_x: f64,
    pub export_row_h: f64,
    pub export_btn_h: f64,
    pub export_field_h: f64,
}

impl Metrics {
    pub fn new(scale: f64) -> Self {
        let scale = normalize_scale(scale);
        let mut metrics = Self {
            ui_scale: scale,
            tooltip_font_size: 11.5,
            tooltip_pad: 7.0 * scale,
            tooltip_offset_x: 12.0 * scale,
            tooltip_offset_y: 18.0 * scale,
            tooltip_margin: 4.0 * scale,
            tooltip_flip_gap: 8.0 * scale,
            dock_tab_content_min_h: 80.0 * scale as f32,
            dock_tab_content_max_h: 480.0 * scale as f32,
            dock_tab_content_default_h: 160.0 * scale as f32,
            palette_pw: 560.0 * scale,
            palette_field_h: 42.0 * scale,
            palette_row_h: 30.0 * scale,
            palette_pad: 8.0 * scale,
            about_width: 900.0 * scale,
            about_height: 633.0 * scale,
            about_corner_radius: 12.0 * scale,
            about_pad_x: 40.0 * scale,
            about_logo_y: 40.0 * scale,
            about_logo_w: 196.0 * scale,
            about_body_top: 128.0 * scale,
            about_link_gap: 22.0 * scale,
            about_wrap_w: 0.0,
            layout_master_min_w: 160.0 * scale,
            layout_master_max_w: 720.0 * scale,
            layout_tools_min_w: 48.0 * scale,
            layout_compact_breakpoint: 240.0 * scale,
            layout_compact_rail_w: 0.0,
            layout_dock_edge: 36.0 * scale,
            layout_dock_seam: 10.0 * scale,
            layout_stack_row_h: 34.0 * scale,
            layout_header_h: 15.0 * scale,
            layout_group_handle_h: 10.0 * scale,
            layout_flyout_w: 280.0 * scale,
            layout_flyout_h: 220.0 * scale,
            newdoc_fh: 30.0 * scale,
            newdoc_footer_h: 62.0 * scale,
            stroke_panel_w: 240.0 * scale,
            stroke_panel_h: 232.0 * scale,
            stroke_panel_pad: 12.0 * scale,
            stroke_panel_ctrl_x: 60.0 * scale,
            stroke_panel_btn_w: 26.0 * scale,
            stroke_panel_btn_h: 20.0 * scale,
            stroke_panel_btn_gap: 7.0 * scale,
            stroke_panel_field_w: 46.0 * scale,
            stroke_panel_step_w: 13.0 * scale,
            workspace_dialog_card_w: 340.0 * scale,
            workspace_dialog_card_h: 132.0 * scale,
            workspace_dialog_manage_w: 320.0 * scale,
            workspace_dialog_row_h: 32.0 * scale,
            workspace_dialog_list_top: 48.0 * scale,
            workspace_dialog_footer_h: 56.0 * scale,
            workspace_dialog_empty_h: 60.0 * scale,
            home_pad: 56.0 * scale,
            home_mark_size: 148.0 * scale,
            home_badge: 46.0 * scale,
            home_target_tile: 172.0 * scale,
            home_min_tile: 128.0 * scale,
            home_max_tile: 224.0 * scale,
            home_toolbar_h: 76.0 * scale,
            picker_w: 680.0 * scale,
            picker_h: 386.0 * scale,
            confirm_close_card_w: 380.0 * scale,
            confirm_close_card_h: 128.0 * scale,
            scroll_view_bar_w: 4.0 * scale,
            scroll_view_min_thumb: 24.0 * scale,
            blenddlg_w: 240.0 * scale,
            blenddlg_pad: 14.0 * scale,
            blenddlg_row_h: 26.0 * scale,
            blenddlg_row_gap: 4.0 * scale,
            blenddlg_field_h: 26.0 * scale,
            blenddlg_btn_h: 30.0 * scale,
            offsetdlg_w: 270.0 * scale,
            offsetdlg_pad: 16.0 * scale,
            offsetdlg_field_h: 26.0 * scale,
            offsetdlg_row_gap: 12.0 * scale,
            offsetdlg_label_w: 90.0 * scale,
            offsetdlg_btn_h: 30.0 * scale,
            xformdlg_w: 320.0 * scale,
            xformdlg_pad: 20.0 * scale,
            xformdlg_row_h: 30.0 * scale,
            xformdlg_radio_r: 6.0 * scale,
            xformdlg_dial_r: 12.0 * scale,
            xformdlg_field_w: 56.0 * scale,
            xformdlg_field_h: 22.0 * scale,
            xformdlg_label_w: 76.0 * scale,
            xformdlg_shear_label_w: 96.0 * scale,
            xformdlg_box_top_gap: 16.0 * scale,
            xformdlg_box_bottom_pad: 14.0 * scale,
            xformdlg_section_gap: 18.0 * scale,
            xformdlg_btn_h: 30.0 * scale,
            xformdlg_btn_w: 80.0 * scale,
            xformdlg_btn_gap: 12.0 * scale,
            xformdlg_bot_pad: 18.0 * scale,
            xformdlg_check_s: 15.0 * scale,
            xformdlg_axis_label_col: 0.0,
            chrome_panel_tab_close_w: 22.0 * scale,
            prefs_w: 660.0 * scale,
            prefs_h: 440.0 * scale,
            prefs_sidebar_w: 168.0 * scale,
            prefs_pad: 22.0 * scale,
            app_guides_rm_w: 168.0 * scale,
            app_guides_rm_row: 24.0 * scale,
            app_guides_rm_pad: 6.0 * scale,
            app_free_transform_ft_btn_w: 30.0 * scale,
            app_free_transform_ft_btn_h: 26.0 * scale,
            app_free_transform_ft_btn_gap: 4.0 * scale,
            app_free_transform_ft_pad: 6.0 * scale,
            app_app_bar_h: (if cfg!(target_os = "windows") {
                0.0
            } else {
                30.0
            }) * scale,
            app_tab_bar_h: 29.4 * scale,
            app_opt_bar_h: 35.0 * scale,
            app_chrome_top: 0.0,
            app_grab_slop: 5.0 * scale,
            app_rail_edge: 4.0 * scale,
            app_drag_threshold: 5.0 * scale,
            app_float_w: 264.0 * scale,
            app_float_h: 320.0 * scale,
            app_fm_row: 22.0 * scale,
            app_at_w: 188.0 * scale,
            app_at_row: 24.0 * scale,
            app_at_pad: 6.0 * scale,
            app_cm_w: 200.0 * scale,
            app_cm_row: 26.0 * scale,
            app_cm_sep: 9.0 * scale,
            app_cm_pad: 6.0 * scale,
            app_pm_w: 168.0 * scale,
            app_pm_row: 28.0 * scale,
            app_pm_sep: 9.0 * scale,
            app_pm_pad: 8.0 * scale,
            app_tool_flyout_w: 220.0 * scale,
            app_tool_flyout_row: 30.0 * scale,
            panels_gradient_natural_h: 238.0 * scale,
            panels_gradient_bar_h: 26.0 * scale,
            panels_gradient_stop_w: 16.0 * scale,
            panels_gradient_stop_h: 15.0 * scale,
            panels_gradient_field_h: 20.0 * scale,
            panels_gradient_chev_w: 15.0 * scale,
            panels_gradient_remove_drop: 30.0 * scale,
            panels_tools_cell: 36.0 * scale,
            panels_tools_top: 4.0 * scale,
            panels_tools_proxy_h: 105.0 * scale,
            panels_align_btn: 26.0 * scale,
            panels_align_gap: 4.0 * scale,
            panels_align_group_gap: 22.0 * scale,
            panels_align_label_drop: 12.0 * scale,
            panels_align_label_to_row: 10.0 * scale,
            panels_align_row_to_rule: 14.0 * scale,
            panels_align_after_rule: 14.0 * scale,
            panels_color_natural_h: 232.0 * scale,
            panels_color_recent_h: 16.0 * scale,
            panels_color_chip: 26.0 * scale,
            panels_color_slider_h: 28.0 * scale,
            panels_color_track_h: 8.0 * scale,
            panels_color_field_w: 58.0 * scale,
            panels_color_spec_h: 16.0 * scale,
            panels_pathfinder_btn: 28.0 * scale,
            panels_pathfinder_gap: 6.0 * scale,
            panels_row_h: 26.0 * scale,
            panels_pad: 10.0 * scale,
            panels_swatch: 22.0 * scale,
            panels_footer_h: 30.0 * scale,
            panels_layers_indent: 14.0 * scale,
            panels_layers_col: 16.0 * scale,
            panels_layers_search_h: 34.0 * scale,
            panels_transform_field_h: 22.0 * scale,
            panels_transform_gap: 8.0 * scale,
            panels_transform_loc: 44.0 * scale,
            panels_character_row_h: 30.0 * scale,
            panels_character_gap: 8.0 * scale,
            panels_character_field_h: 24.0 * scale,
            panels_paragraph_btn: 27.0 * scale,
            panels_paragraph_bgap: 3.0 * scale,
            panels_paragraph_field_h: 24.0 * scale,
            panels_paragraph_row: 32.0 * scale,
            shapedialog_spiral_btn: 40.0 * scale,
            shapedialog_spiral_btn_gap: 10.0 * scale,
            shapedialog_spiral_label_w: 96.0 * scale,
            shapedialog_spiral_top_pad: 10.0 * scale,
            shapedialog_spiral_bot_pad: 10.0 * scale,
            shapedialog_spiral_options_h: 0.0,
            shapedialog_w: 268.0 * scale,
            shapedialog_btn_h: 30.0 * scale,
            shapedialog_btn_w: 88.0 * scale,
            shapedialog_btn_gap: 14.0 * scale,
            shapedialog_gap_before_btns: 18.0 * scale,
            shapedialog_bot_pad: 16.0 * scale,
            shapedialog_sizing_pad_x: 20.0 * scale,
            shapedialog_sizing_top_pad: 18.0 * scale,
            shapedialog_sizing_field_h: 24.0 * scale,
            shapedialog_sizing_row_stride: 42.0 * scale,
            shapedialog_sizing_label_w: 66.0 * scale,
            shapedialog_sizing_link_w: 26.0 * scale,
            shapedialog_sizing_step_w: 15.0 * scale,
            shapedialog_arc_row_h: 26.0 * scale,
            shapedialog_arc_row_gap: 10.0 * scale,
            shapedialog_arc_label_w: 96.0 * scale,
            shapedialog_arc_top_pad: 6.0 * scale,
            shapedialog_arc_bot_pad: 10.0 * scale,
            shapedialog_arc_options_h: 0.0,
            context_bar_align_btn: 25.0 * scale,
            context_bar_align_gap: 2.0 * scale,
            context_bar_align_group: 9.0 * scale,
            context_bar_align_drop_w: 37.0 * scale,
            context_bar_align_width: 0.0,
            context_bar_anchor_btn: 25.0 * scale,
            context_bar_gap: 25.0 * scale,
            export_w: 900.0 * scale,
            export_h: 600.0 * scale,
            export_pad: 24.0 * scale,
            export_right_x: 540.0 * scale,
            export_row_h: 26.0 * scale,
            export_btn_h: 30.0 * scale,
            export_field_h: 24.0 * scale,
        };
        metrics.layout_compact_rail_w = metrics.layout_tools_min_w;
        metrics.app_chrome_top =
            metrics.app_app_bar_h + metrics.app_tab_bar_h + metrics.app_opt_bar_h;
        metrics.shapedialog_arc_options_h = metrics.shapedialog_arc_top_pad
            + 3.0 * metrics.shapedialog_arc_row_h
            + 2.0 * metrics.shapedialog_arc_row_gap
            + metrics.shapedialog_arc_bot_pad;
        metrics.shapedialog_spiral_options_h = metrics.shapedialog_spiral_top_pad
            + metrics.shapedialog_spiral_btn
            + metrics.shapedialog_spiral_bot_pad;
        metrics.xformdlg_axis_label_col =
            metrics.xformdlg_radio_r * 2.0 + 12.0 * scale + metrics.xformdlg_label_w;
        metrics.about_wrap_w =
            (metrics.about_width * 0.39 - metrics.about_pad_x - 24.0 * scale) as f32;
        metrics.context_bar_align_width = metrics.context_bar_align_drop_w
            + 14.0 * scale
            + 2.0
                * (6.0 * metrics.context_bar_align_btn
                    + 5.0 * metrics.context_bar_align_gap
                    + metrics.context_bar_align_group);
        metrics
    }
}

pub fn normalize_scale(scale: f64) -> f64 {
    if scale.is_finite() {
        scale.clamp(1.0, 1.5)
    } else {
        1.0
    }
}

thread_local! {
    static CURRENT: RefCell<Metrics> = RefCell::new(Metrics::new(1.0));
}

/// All chrome reads on the UI thread observe the same applied preference.
pub fn with<T>(read: impl FnOnce(&Metrics) -> T) -> T {
    CURRENT.with(|m| read(&m.borrow()))
}

pub fn apply(scale: f64) {
    CURRENT.with(|m| *m.borrow_mut() = Metrics::new(scale));
}

/// Scale an inline chrome distance; never use for ratios or document values.
pub fn px(value: f64) -> f64 {
    with(|m| value * m.ui_scale)
}

/// Enough room for the preferences card, compact rails and the top chrome.
pub fn main_min_size() -> (f64, f64) {
    with(|m| {
        (
            m.prefs_w + 2.0 * m.prefs_pad,
            m.prefs_h + m.app_chrome_top + 2.0 * m.prefs_pad,
        )
    })
}
